const { query } = require('../config/db');
async function list(user) { const params = []; let where = ''; if (user?.role === 'SALES_REP') { where = 'WHERE q.sales_rep_id = ?'; params.push(user.id); } if (user?.role === 'CUSTOMER') { where = 'WHERE q.customer_id = ?'; params.push(user.customer_id); } return query(`SELECT q.*, c.name AS customer_name, u.name AS sales_rep_name FROM quotations q JOIN customers c ON c.id = q.customer_id JOIN users u ON u.id = q.sales_rep_id ${where} ORDER BY q.updated_at DESC`, params); }
async function findById(id) { const rows = await query('SELECT q.*, c.name AS customer_name, u.name AS sales_rep_name FROM quotations q JOIN customers c ON c.id = q.customer_id JOIN users u ON u.id = q.sales_rep_id WHERE q.id = ?', [id]); if (!rows[0]) return null; rows[0].items = await query('SELECT qi.*, p.name AS product_name, p.sku FROM quotation_items qi JOIN products p ON p.id = qi.product_id WHERE qi.quotation_id = ? ORDER BY qi.id', [id]); return rows[0]; }
async function create(data) { const result = await query('INSERT INTO quotations (customer_id, sales_rep_id, price_list_id, valid_until) VALUES (?, ?, ?, ?)', [data.customer_id, data.sales_rep_id, data.price_list_id || null, data.valid_until || null]); return findById(result.insertId); }
async function update(id, data) { await query('UPDATE quotations SET customer_id = COALESCE(?, customer_id), price_list_id = COALESCE(?, price_list_id), valid_until = COALESCE(?, valid_until), status = COALESCE(?, status) WHERE id = ?', [data.customer_id ?? null, data.price_list_id ?? null, data.valid_until ?? null, data.status ?? null, id]); return findById(id); }
async function addItem(quotationId, data) { const result = await query('INSERT INTO quotation_items (quotation_id, product_id, variant_id, quantity, unit_price, discount_percent, tax_percent, line_total) SELECT ?, p.id, ?, ?, COALESCE(?, p.base_price), ?, COALESCE(?, p.tax_percent), 0 FROM products p WHERE p.id = ?', [quotationId, data.variant_id || null, data.quantity, data.unit_price ?? null, data.discount_percent || 0, data.tax_percent ?? null, data.product_id]); await recalculate(quotationId); return query('SELECT * FROM quotation_items WHERE id = ?', [result.insertId]).then(rows => rows[0]); }
async function updateItem(id, data) { const item = await query('SELECT quotation_id FROM quotation_items WHERE id = ?', [id]); if (!item[0]) return null; await query('UPDATE quotation_items SET quantity = COALESCE(?, quantity), unit_price = COALESCE(?, unit_price), discount_percent = COALESCE(?, discount_percent), tax_percent = COALESCE(?, tax_percent), variant_id = COALESCE(?, variant_id) WHERE id = ?', [data.quantity ?? null, data.unit_price ?? null, data.discount_percent ?? null, data.tax_percent ?? null, data.variant_id ?? null, id]); await recalculate(item[0].quotation_id); return query('SELECT * FROM quotation_items WHERE id = ?', [id]).then(rows => rows[0]); }
async function removeItem(quotationId, itemId) { await query('DELETE FROM quotation_items WHERE id = ? AND quotation_id = ?', [itemId, quotationId]); await recalculate(quotationId); }
async function recalculate(id) { await query(`UPDATE quotation_items qi JOIN products p ON p.id = qi.product_id SET qi.discount_amount = ROUND(qi.unit_price * qi.quantity * qi.discount_percent / 100, 2), qi.tax_amount = ROUND((qi.unit_price * qi.quantity - qi.discount_amount) * qi.tax_percent / 100, 2), qi.line_total = ROUND(qi.unit_price * qi.quantity - qi.discount_amount + qi.tax_amount, 2), qi.cost_amount = ROUND(p.cost_price * qi.quantity, 2), qi.margin_amount = ROUND(qi.unit_price * qi.quantity - qi.discount_amount - qi.cost_amount, 2), qi.margin_percent = IF(qi.unit_price * qi.quantity - qi.discount_amount = 0, 0, ROUND(qi.margin_amount * 100 / (qi.unit_price * qi.quantity - qi.discount_amount), 2)) WHERE qi.quotation_id = ?`, [id]); await query(`UPDATE quotations q JOIN (SELECT quotation_id, COALESCE(SUM(unit_price * quantity), 0) subtotal, COALESCE(SUM(discount_amount), 0) discount_amount, COALESCE(SUM(tax_amount), 0) tax_amount, COALESCE(SUM(line_total), 0) total_amount, COALESCE(SUM(margin_amount), 0) margin_amount FROM quotation_items WHERE quotation_id = ? GROUP BY quotation_id) x ON x.quotation_id = q.id SET q.subtotal = x.subtotal, q.discount_amount = x.discount_amount, q.tax_amount = x.tax_amount, q.total_amount = x.total_amount, q.margin_amount = x.margin_amount, q.margin_percent = IF(x.subtotal - x.discount_amount = 0, 0, x.margin_amount * 100 / (x.subtotal - x.discount_amount)) WHERE q.id = ?`, [id, id]); }
async function submit(id, userId) { const current = await query('SELECT status FROM quotations WHERE id = ?', [id]); if (!current[0]) return null; await query('UPDATE quotations SET status = \'SENT\', last_activity_at = CURRENT_TIMESTAMP WHERE id = ?', [id]); await query('INSERT INTO quotation_status_history (quotation_id, old_status, new_status, changed_by) VALUES (?, ?, \'SENT\', ?)', [id, current[0].status, userId || null]); return findById(id); }
module.exports = { list, findById, create, update, addItem, updateItem, removeItem, submit, recalculate };
